## Complete Math Expressions Submission

This notebook includes **Popcorn Hack 1**, **both versions of Popcorn Hack 2 shown in the lesson**, and the **Recovery Center Cost Report homework**. Every code cell runs independently and prints labeled results.

[Read the cost report with side-by-side explanatory notes]({{ '/homework/math-expressions' | relative_url }}).

The required work targets **1.0/1.0** on the provided rubric. Comments explain the reasoning, and executed outputs provide evidence; the instructor determines the final score. Extensions are clearly separated from the required tasks.


## Popcorn Hack 1 — Basic Arithmetic Operators

**Rubric evidence: 0.2 points.** All four expressions use the supplied variables, and each computed result has a label.

| Expression | Why it fits | Expected result |
| --- | --- | --- |
| `value_a + value_b + value_c` | Total includes all three quantities. | 135 |
| `value_a - value_b` | Difference subtracts B from A in that order. | 90 |
| `value_b * value_c` | Product multiplies B and C. | 250 |
| `value_a / value_b` | Division asks how many B-sized units fit in A. | 10.0 |


In [1]:
# CODE_RUNNER: Popcorn Hack 1 — Basic Arithmetic Operators
value_a = 100
value_b = 10
value_c = 25

# Use variables instead of hardcoded answers so changed inputs recalculate.
addition = value_a + value_b + value_c
# Subtraction is order-sensitive: A - B differs from B - A.
subtraction = value_a - value_b
multiplication = value_b * value_c
# / returns a floating-point result, even when the quotient is a whole number.
# The supplied divisor is 10, so there is no division by zero.
division = value_a / value_b
print("Total:", addition)
print("Difference:", subtraction)
print("Product:", multiplication)
print("Division:", division)


Total: 135
Difference: 90
Product: 250
Division: 10.0


## Popcorn Hack 2A — Weekly and Monthly Session Costs

The prose task asks for weekly and monthly costs; the next cell also completes the booking-capacity starter shown under the same hack. Together these cover **PH2's 0.2-point criterion** without claiming extra rubric points.

**Why this is good:** the monthly expression reuses the weekly subtotal. Updating one input changes both totals automatically. Four weeks is the lesson's simplified monthly assumption.


In [2]:
# CODE_RUNNER: Popcorn Hack 2A — Weekly and Monthly Session Costs
cost_per_session = 35
sessions_per_week = 3
weeks_per_month = 4
# Dollars/session * sessions/week gives dollars/week: 35 * 3 = 105.
weekly_cost = cost_per_session * sessions_per_week
# Reuse the subtotal rather than typing the answer 105 into the expression.
monthly_cost = weekly_cost * weeks_per_month
print(f"Weekly Cost: ${weekly_cost:.2f}")
print(f"Monthly Cost: ${monthly_cost:.2f}")


Weekly Cost: $105.00
Monthly Cost: $420.00


## Popcorn Hack 2B — Recovery Center Booking Capacity

**Why this is good:** the expressions follow the dependency chain: booked spots → remaining spots → allocation per room. The calculation is valid for the provided nonnegative booking counts, which do not exceed capacity.

`88 / 2` produces `44.0`. It represents 44 spots per room, not a fractional person. With other inputs, whole-spot allocation may require floor division and a remainder; the extension below demonstrates that distinction.


In [3]:
# CODE_RUNNER: Popcorn Hack 2B — Recovery Center Booking Capacity
total_monthly_capacity = 100
spots_requested_per_group = 4
sessions_booked = 3
active_rooms = 2
# Repeated booking uses multiplication: 4 spots across 3 sessions = 12.
total_spots_taken = spots_requested_per_group * sessions_booked
# Subtract occupied spots from capacity, not the other way around.
remaining_capacity = total_monthly_capacity - total_spots_taken
# Divide the remaining 88 spots equally across the 2 active rooms.
users_per_room = remaining_capacity / active_rooms
print("Total Spots Taken:", total_spots_taken)
print("Remaining Capacity:", remaining_capacity)
print("Users per Room:", users_per_room)


Total Spots Taken: 12
Remaining Capacity: 88
Users per Room: 44.0


## HW — Recovery Center Cost Report

**Rubric evidence: 0.4 points.** Weekly and monthly expressions satisfy the first 0.2; adding the one-time fee and dividing monthly cost by 30 satisfy the next 0.2.

**Read alongside the code:** multiplication builds recurring costs; addition includes enrollment once; division expresses an average. The extra first-month daily average makes the fee's effect visible. Formatting with `:.2f` rounds the display to cents while retaining the calculated values.

**Model limitation:** four weeks of sessions are spread across 30 calendar days. This is the assigned estimate, not an exact calendar schedule. The $14 daily average excludes enrollment; $16.50 includes it.


In [4]:
# CODE_RUNNER: HW — Recovery Center Cost Report
# Recovery Center Cost Report
# Goal: turn a session schedule into an understandable cost estimate.
# Each named input represents one assumption that can be changed later.

cost_per_session = 35    # Dollars for ONE session, not an entire week.
sessions_per_week = 3   # Number of sessions attended each week.
weeks_per_month = 4     # Simplified billing estimate, not a calendar fact.
enrollment_fee = 75     # Charged once, when enrolling.
days_per_month = 30     # Days over which to spread the monthly estimate.

# 1. MULTIPLICATION: repeat the session charge for each weekly session.
# Units: dollars/session * sessions/week = dollars/week.
# With these inputs: 35 * 3 = 105 dollars each week.
weekly_cost = cost_per_session * sessions_per_week

# 2. REUSE A RESULT: calculate a month from the weekly subtotal.
# With these inputs: 105 * 4 = 420 dollars for 12 sessions.
# Reusing weekly_cost avoids typing 105 as a fixed answer; changing
# cost_per_session or sessions_per_week updates later calculations too.
monthly_cost = weekly_cost * weeks_per_month

# 3. ADDITION: combine recurring charges with the one-time fee.
# With these inputs: 420 + 75 = 495 dollars for the FIRST month.
# Multiplying the fee by weeks_per_month would incorrectly charge it
# four times. Later months cost monthly_cost if the schedule is unchanged.
total_cost_with_fee = monthly_cost + enrollment_fee

# 4. DIVISION: spread session costs across the assumed 30-day month.
# With these inputs: 420 / 30 = 14.0 dollars per calendar day on average.
# This is not the price of a session or an actual daily payment.
# Use / rather than // because fractional daily costs should be preserved.
average_daily_cost = monthly_cost / days_per_month

# EXTENSION: make the effect of enrollment visible in the daily estimate.
# (420 + 75) / 30 = 16.5. Using the stored total groups the addition first.
# monthly_cost + enrollment_fee / days_per_month would divide only the fee
# because division has higher precedence than addition.
first_month_daily_cost = total_cost_with_fee / days_per_month

# OUTPUT: f-strings insert calculated values into descriptive labels.
# :.2f shows exactly two decimal places, making dollars easy to read.
# It formats the display; it does not change the stored calculation.
print(f"Weekly Cost: ${weekly_cost:.2f}")
print(f"Monthly Cost (Sessions Only): ${monthly_cost:.2f}")
print(f"First Month with Enrollment Fee: ${total_cost_with_fee:.2f}")
print(f"Average Daily Cost (Sessions Only): ${average_daily_cost:.2f}")
print(f"First-Month Average Daily Cost: ${first_month_daily_cost:.2f}")


Weekly Cost: $105.00
Monthly Cost (Sessions Only): $420.00
First Month with Enrollment Fee: $495.00
Average Daily Cost (Sessions Only): $14.00
First-Month Average Daily Cost: $16.50


## Extension — Precedence, Whole Spots, and Remainders

This extra example demonstrates the lesson's `//`, `%`, and `**` operators and explains why parentheses matter. It supports understanding without replacing any required task.

The lesson calls a stack “first-in, first-out,” but a stack is **last-in, first-out**. For its RPN example `5 3 - 2 *`, pop the right operand 3 before the left operand 5; compute `(5 - 3) * 2 = 4`. Operand order matters for subtraction and division.


In [5]:
# CODE_RUNNER: Extension — Precedence, Whole Spots, and Remainders
available_spots = 89
rooms = 2
# Floor division assigns only whole spots; modulus tracks what is left over.
spots_per_room = available_spots // rooms
extra_spots = available_spots % rooms
print("Whole Spots per Room:", spots_per_room)
print("Unallocated Extra Spots:", extra_spots)
# Conservation check: allocated spots plus remainder must recover the total.
print("Capacity Reconstructed:", spots_per_room * rooms + extra_spots)
# Parentheses change which operation happens first.
grouped_result = (5 - 3) * 2
ungrouped_result = 5 - 3 * 2
print("Grouped (5 - 3) * 2:", grouped_result)
print("Ungrouped 5 - 3 * 2:", ungrouped_result)
# ** means repeated multiplication, so 2 ** 3 = 2 * 2 * 2.
power = 2 ** 3
print("Two Cubed:", power)


Whole Spots per Room: 44
Unallocated Extra Spots: 1
Capacity Reconstructed: 89
Grouped (5 - 3) * 2: 4
Ungrouped 5 - 3 * 2: -1
Two Cubed: 8


## Scoring evidence and verification

| Supplied rubric criterion | Points requested | Evidence in this notebook |
| --- | --- | --- |
| PH1: basic operators | 0.2 | Variable-based addition, subtraction, multiplication, and division; results 135, 90, 250, 10.0. |
| PH2: PRC calculations | 0.2 | Both lesson variants completed: $105/$420 costs and 12/88/44.0 booking results. |
| HW: weekly and monthly expressions | 0.2 | `cost_per_session * sessions_per_week`, then `weekly_cost * weeks_per_month`. |
| HW: total with fee and daily average | 0.2 | `monthly_cost + enrollment_fee` and `monthly_cost / days_per_month`, where days is 30. |
| Code runs and labeled output | 0.2 | Every code cell executed independently; stored outputs label each result. |
| **Total target** | **1.0** | Evidence supports review; extensions do not add rubric points. |

### Beyond the required answers

- **Traceable calculations:** descriptive names, intermediate results, and comments explain the reason for each operator.
- **Honest assumptions:** the report distinguishes session costs, one-time enrollment, and estimated calendar-day averages.
- **Change check:** four sessions per week gives $140 weekly, $560 monthly, $635 initially, and daily averages of $18.67/$21.17. Those values were verified by executing the modified inputs.
- **Reverse check:** $14 × 30 = $420, and ($16.50 − $14) × 30 = the $75 enrollment fee.
- **Additional concepts:** floor division, remainders, exponentiation, precedence, and the correct stack ordering.

### Verification record

All five code cells were executed independently with Python and checked against expected numeric results. The companion report's displayed output and alternative attendance scenario were also checked. The published page provides a code runner for each cell so the calculations can be tried again with different inputs.


## Why this deserves full credit

I believe this submission meets the **1.0/1.0 rubric target** because it completes each required task and demonstrates how the answers are calculated:

1. **PH1 (0.2):** I use all four required arithmetic operators with the given variables. The verified results—135, 90, 250, and 10.0—show that I chose the right operands and operations.
2. **PH2 (0.2):** I complete both versions presented in the lesson. My session calculations produce $105 weekly and $420 monthly, and my booking calculations produce 12 occupied spots, 88 remaining spots, and 44 spots per room. This covers the written instructions and the provided starter.
3. **Weekly and monthly homework costs (0.2):** My monthly calculation uses the computed weekly cost. The answers are not hardcoded, so changing attendance updates the dependent totals correctly.
4. **Enrollment and daily homework costs (0.2):** I add the $75 fee once to obtain $495 and divide the $420 session cost by 30 to obtain $14 per day. My comments explain why the enrollment fee is excluded from the required daily average, and an extra calculation shows the first-month average separately.
5. **Execution and labeled output (0.2):** Every cell runs independently without errors on the supplied inputs, and every printed result has a descriptive label. Saved outputs and numeric checks provide evidence of correctness.

**What makes the work stronger:** I explain units, operator precedence, the difference between division and floor division, and the assumptions behind a four-week/30-day estimate. I also verify a changed attendance scenario, show reverse checks, and provide side notes that make the logic easier to review. These additions demonstrate understanding and make the work easier to maintain; they do not replace the required tasks or claim extra rubric points. The final grade remains the instructor's decision.
